### ISSUE TITLE
Tạo và xây dựng cơ sở dữ liệu

### ISSUE THREAD

**Issue by MinaNguyen99** [NongThiMinh123/SE03-Group12#11]

**Comment by Dieungan99** [comment]
Với mỗi mục lớn thì mình tạo 1 table riêng nhỉ

**Comment by quynhnhi0124** [comment]
chọn mục đi mn, về cơ bản thì một trang web bán mĩ phầm cần có gì dc nhỉ

**Comment by NongThiMinh123** [comment]
T thấy là skincare, makeup. Gì nữa nhỉ

**Comment by NongThiMinh123** [comment]
Alo.mọi người ơi, database thì đưa lên hỗ nào trên git nhỉ .

**Comment by quynhnhi0124** [comment]
ko phải đưa lên đâu, t nghĩ thế

**Comment by quynhnhi0124** [comment]
@NongThiMinh123 tạo lun cái repo dần đi là vừa nà

**Comment by Dieungan99** [comment]
h mình thống nhất các mục sp r tạo csdl nhá

**Comment by MinaNguyen99** [comment]
mỹ phẩm thì có khá nhiều 
mình có thể tham khảo mấy trang web mỹ phẩm thử

**Comment by quynhnhi0124** [comment]
T có xem qua một vài trang, thì thấy cơ bản nhất là có hai mục sp là trang điểm và skincare, trong hai mục đấy bao gồm cả các mục con thì sau khi bàn về các đề mục nhóm mình thảo luận sau. Nhưng mỗi 2 mục như vậy thì hơi thiếu đúng ko mn

**Comment by MinaNguyen99** [comment]
t cũng cảm thấy hơi thiếu thiêú

**Comment by MinaNguyen99** [comment]
nhưng trước mắt chúng ta cứ làm trước hai  mục đấy hoàn thành trước đã còn những phần sau sẽ bàn tiếp nữa

**Comment by NongThiMinh123** [comment]
Ừ.cứ cùng nhau làm đi đã .xong đến dfaau up bài lên đến đó nhé

**Comment by quynhnhi0124** [comment]
Vì tiến độ của nhóm đang còn chậm, mong mn góp í và xong luôn phân công xây dựng cơ sở dữ liệu nhé.
Trang web chúng mình sẽ bán sp về những mục (skincare, makeup, hair, bath&body, functional foods, beauty tools). Phần này thì @Dieungan99 bảo vs t là đang làm dở rồi, trong vòng hnay sẽ xong và push lên luôn, sau khi Minh tạo repo. Sau khi hoàn thành mình sẽ tiến hành tạo khoá ngoại và xem phần ORM sau nhé.

Phần trang chủ, t cũng đang làm và sắp hoàn thành rồi, đợi Ngân đưa csdl lên t sẽ hoàn thành nốt phần trang chủ rồi đưa lên cho mn. Ngân cũng làm phần kết nối dữ liệu luôn.
Phần đăng nhập và đăng kí @NongThiMinh123 hoàn thành sớm nha.

Phần header và footer mn sẽ có file riêng, sau khi t gửi lên trang chủ thì @Hamyho sd để tạo những trang tiếp theo nhé.

Sau khi có những cái trên thì mình sẽ bắt đầu thống nhất những phần sau nhé, nhắc lại là nhóm đang chậm tiến trình nên mình mong mn hoàn thành trong đúng khoảng tgian

**Comment by NongThiMinh123** [comment]
oke ,, nhưng mà m ơi,, cơ sở dữ liệu mà Ngân làm ấy thì có cần  post lên đây k nhỉ

**Comment by NongThiMinh123** [comment]
nếu mà post lên thì @Dieungan99  xuất cơ sở dữ liệu ra rồi lưu vào 1 file, tất cả các bảng thì tương ứng vs các file cho vào 1 folder  và  up lên nha

**Comment by quynhnhi0124** [comment]
T nghĩ là cần đó

**Comment by NongThiMinh123** [comment]
Alo...mn ơi.lên git đi ..t sẽ tạo user và phần đăng nhập  và đăng kí nhá....giao diện sẽ ntn đây

**Comment by NongThiMinh123** [comment]
thống nhất tên databse của mình là NMN nha và username='root', pass=' ', vì khi mình cài đặt trong database mỗi lần pull về cài lại thì lại khó
