### ISSUE TITLE
Bàn về giao diện của website

### ISSUE THREAD

**Issue by MinaNguyen99** [NongThiMinh123/SE03-Group12#12]
Bao gồm theme, phân bố các mục,....

**Comment by quynhnhi0124** [comment]
theme trắng xám một tí dc ko mn, nhìn cho sang một tí ( vì đây là trang bán hàng làm đẹp )

**Comment by Dieungan99** [comment]
uh t cũng thích gam lạnh hơn nóng :)))
Với tham khảo các web bán mỹ phẩm khác thấy nó cứ màu mè nhìn bị lòe loẹt :)))

**Comment by NongThiMinh123** [comment]
Giao diện phân ra các mục nhỏ sao cho khách hành tìm sản phẩm dễ hơn nhé

**Comment by NongThiMinh123** [comment]
Mn ơi...tý t tạo project, xong up lên trên này mn clone về lm nha

**Comment by NongThiMinh123** [comment]
Phần đăng nhập, đăng xuất ,và đăng kí của t sẽ cho thêm bảng databse nữa nhê
