### ISSUE TITLE
Hoàn thiện giao diện trang chủ

### ISSUE THREAD

**Issue by MinaNguyen99** [NongThiMinh123/SE03-Group12#18]
hoàn thiện code trang chủ website và up lên nha mọi người , để theo kịp tiến độ nhé

**Comment by quynhnhi0124** [comment]
T đã tạo pull request, đợi @NongThiMinh123 xem và merge giúp t với nha.

**Comment by quynhnhi0124** [comment]
mn pull về xem qua rồi có gì thì góp í nha, đây là giao diện nên cũng xem ở phần nhìn thôi (font chữ, theme, bố cục sản phẩm,...). T thấy phần này cũng khá quan trọng đó, quyết định xong thì tất cả các blade tiếp theo của trang web sẽ sd header, footer, font chữ, ... nên mn góp í thoải mái nha!!!

**Comment by NongThiMinh123** [comment]
![picture1](https://user-images.githubusercontent.com/54107714/69004981-cb876000-094d-11ea-8561-8be2b299962b.PNG)

**Comment by NongThiMinh123** [comment]
dòng số 24 bị lỗi Nhi ạ ,k biết bị sai ở đâu,, lúc m tạo xong giao diện trang chủ có chạy được k

**Comment by NongThiMinh123** [comment]
Nhi ơi.,Nhi pull về xme lại nha

**Comment by MinaNguyen99** [comment]
xóa 2 dòng thừa đi nha

**Comment by Hamyho** [comment]
Xong trong views ấy có một folder layout có cái tên là master ấy up cái đấy lên

**Comment by MinaNguyen99** [comment]
nhi  đang sửa hiện tên người dùng trên trang chủ đúng k?

**Comment by MinaNguyen99** [comment]
@NongThiMinh123  minh đưa cái bảng SQL lên sớm nha minh

**Comment by MinaNguyen99** [comment]
à với cả là t sẽ ko để hiện tên người dùng đâu, để sau @NongThiMinh123  đưa cái bảng user lên rồi  mình mới thêm vào

**Comment by quynhnhi0124** [comment]
um t đang xem phần @Hamyho  hỏi nhé

**Comment by NongThiMinh123** [comment]
mọi người đang làm tơi đâu r
