### ISSUE TITLE
Nhóm thảo luận về tên đề tài

### ISSUE THREAD

**Issue by MinaNguyen99** [NongThiMinh123/SE03-Group12#2]
Tên đề tài được đặt bằng tiếng anh.
Tên đề tài ngắn gọn, súc tích, ít chữ nhất nhưng đẩy đủ thông tin đề tài
 Hi vọng mọi người cho ý kiến sớm.

**Comment by Dieungan99** [comment]
Mình làm website bán hàng nhé

**Comment by quynhnhi0124** [comment]
Mỹ phẩm dc ko mn, cho dễ tìm ảnh tìm các thứ làm data í

**Comment by Dieungan99** [comment]
Ừa website bán mỹ phẩm nhá để chọn ảnh cho đẹp nè

**Comment by MinaNguyen99** [comment]
chốt website bán mỹ phẩm nha

**Comment by MinaNguyen99** [comment]
nên đặt tên gì cho project này đây mọi người

**Comment by Dieungan99** [comment]
NMNM Comestic :)))

**Comment by NongThiMinh123** [comment]
T thấy mình nên đặt tên rõ ràng thêm chút, súc tích và ý nghĩa hơn nhỉ

**Comment by MinaNguyen99** [comment]
2NM Comestic project???

**Comment by quynhnhi0124** [comment]
mn quyết nhanh rùi phân công luôn nhỉ, tại nhóm mình cx đang muộn nhỉ đúng ko

**Comment by Dieungan99** [comment]
Uh ngắn gọn súc tích đấy :)))

**Comment by Dieungan99** [comment]
Thôi chốt tên nhóm vậy luôn nhá

**Comment by MinaNguyen99** [comment]
Thế thì chốt tên project nha

**Comment by Dieungan99** [comment]
Ok

**Comment by Dieungan99** [comment]
Bọn mình viết bằng ngôn ngữ PHP, frame work Laravel nha

**Comment by MinaNguyen99** [comment]
2NM Comestic

**Comment by NongThiMinh123** [comment]
Hà My thêm đề tài  vào readme đi nha

**Comment by NongThiMinh123** [comment]
Kết hợp thêm javascrip nữa nhỉ..

**Comment by quynhnhi0124** [comment]
framework laravel nữa My nha cho tiện

**Comment by quynhnhi0124** [comment]
à Ngân bảo trên kia r

**Comment by Dieungan99** [comment]
MVC nữa nha

**Comment by NongThiMinh123** [comment]
Chốt vậy nha, thế giờ đóng issue này để bọn mình giải quyết issue khác
