### ISSUE TITLE
thống nhất phương pháp làm việc giữa các branch trên git

### ISSUE THREAD

**Issue by MinaNguyen99** [NongThiMinh123/SE03-Group12#21]
1. khi clone code về mọi người dùng leejng $git checkout develop để vào branch develop để thêm/xóa/sửa/cập nhật code 
2. Khi add vào dùng lệnh $git add . để thêm vào tất cả. sau đấy $git commit -m "update something" để commit lại những gì mình thay đổ
3. Lệnh $git push origin master do sau khi add mới ở HEAD nên dùng lệnh này
4. Lệnh $git push để push code lên
5. Lệnh $ git merge develop để merge develop với master

**Comment by NongThiMinh123** [comment]
Ok

**Comment by NongThiMinh123** [comment]
Tức là khi almf xo g mình sẽ merge luôn vào master chứ

**Comment by NongThiMinh123** [comment]
Merge vào develop r merge vào master luôn chứ

**Comment by quynhnhi0124** [comment]
Cho t hỏi với, push origin là lên dev chứ nhỉ, vào dev xong testing rồi mới cho merge vào master

**Comment by NongThiMinh123** [comment]
> Cho t hỏi với, push origin là lên dev chứ nhỉ, vào dev xong testing rồi mới cho merge vào master

Ừ, lm theo quy trình như vậy, sau khi test xong thì merge vào master

**Comment by NongThiMinh123** [comment]
Nhưng mỗi lần mà mọi người pull về thi là pull bên develop là dữ liệu được thay đổi mới nhất

**Comment by MinaNguyen99** [comment]
t thấy chỉ cần làm đúng như vậy là nó có ở cả hai ý
