### ISSUE TITLE
Thảo luận trong quá trình hoàn thiện trang web

### ISSUE THREAD

**Issue by NongThiMinh123** [NongThiMinh123/SE03-Group12#22]
alo ,mn làm tới đâu rồi

**Comment by Dieungan99** [comment]
m ơi t đang làm cái show sp ra nhá

**Comment by NongThiMinh123** [comment]
ok ,,t cũng đang hoàn thiện dần đăng nhập ,đăng kí , và đăng xuất rồi

**Comment by NongThiMinh123** [comment]
đến bây giờ thì mỗi người đều sắp xong phần của mình rồi, chia tiếp công việc cùng nhau làm nha ,

**Comment by Dieungan99** [comment]
ok

**Comment by MinaNguyen99** [comment]
T đang phân công làm nốt các phần chi tiết của trang .Sau khi phần này kết thúc thì Front của mình sẽ xong

**Comment by NongThiMinh123** [comment]
t sau  khi làm xog đăng kí ,đăng nhập vs lại đăng xuất thì sẽ làm thêm phần quản lí sap cũng như quản lí đơn hàng

**Comment by NongThiMinh123** [comment]
alo , taastt cả mn lam đến đâu rồi , xem gần hoàn thiện chưa, nay mùng 4 rồi đấy

**Comment by MinaNguyen99** [comment]
cũng gần xong hết rồi đấy

**Comment by Dieungan99** [comment]
Đang xem lại tí cho hoàn chỉnh đây

**Comment by Dieungan99** [comment]
Ơ thế có lm bản word ko đó?

**Comment by NongThiMinh123** [comment]
có chứ

**Comment by NongThiMinh123** [comment]
làm bản word nữa nha ,

**Comment by Dieungan99** [comment]
Vậy đợi xong rồi mới làm hay lm đến đâu word đến đó luôn?

**Comment by NongThiMinh123** [comment]
bắt đầu làm từ bây giờ đi

**Comment by NongThiMinh123** [comment]
nay cũng mùng 4 rồi

**Comment by quynhnhi0124** [comment]
t lam cai gio hang, co su dung composer package, co gi t gui link cai dat cho mn nhe

**Comment by NongThiMinh123** [comment]
làm đến đâu cập nhật đến đấy luôn

**Comment by NongThiMinh123** [comment]
> t lam cai gio hang, co su dung composer package, co gi t gui link cai dat cho mn nhe

ok , tý gửi lên đây luôn nha

**Comment by MinaNguyen99** [comment]
thế cách cài đặt cũng ghi vào readme chứ

**Comment by NongThiMinh123** [comment]
ừ ,có chứ  nhỉ

**Comment by NongThiMinh123** [comment]
mà có phần hướng dẫn sử dụng trang web k mn

**Comment by MinaNguyen99** [comment]
mình có cần kiểu hướng dẫn sử dụng k mọi ng

**Comment by MinaNguyen99** [comment]
đấy t cũng nghĩ như v

**Comment by NongThiMinh123** [comment]
thế hướng dẫn sử dụng cũn ghi vào readme hay tạo word riêng

**Comment by Dieungan99** [comment]
cả 2 luôn đi

**Comment by MinaNguyen99** [comment]
t nghĩ có lẽ bỏ cả 2 cũng đc

**Comment by MinaNguyen99** [comment]
nhưng mà thầy yêu cầu làm word à c

**Comment by quynhnhi0124** [comment]
ua sao bo di do t tuong cx can de nho co cham sp

**Comment by Dieungan99** [comment]
t có bt đâu hỏi thì Minh bảo làm đó

**Comment by NongThiMinh123** [comment]
> t nghĩ có lẽ bỏ cả 2 cũng đc

sao lại bỏ đó

**Comment by NongThiMinh123** [comment]
tại t thấy làm cái j thì đều làm word mà

**Comment by Dieungan99** [comment]
mà bỏ cả 2 là bỏ cái j đấy

**Comment by quynhnhi0124** [comment]
@Dieungan99 word + readme as

**Comment by NongThiMinh123** [comment]
thế tức là k có phần hướng dẫn sử dụng à

**Comment by Dieungan99** [comment]
á thế đâu đc readme phải có chứ thầy còn yêu cầu readme các kiểu mà

**Comment by Dieungan99** [comment]
t nghĩ là phải có hdsd chứ

**Comment by MinaNguyen99** [comment]
ý bỏ là có cả 2 :)

**Comment by MinaNguyen99** [comment]
bỏ vào ý

**Comment by quynhnhi0124** [comment]
la sao :(

**Comment by NongThiMinh123** [comment]
> bỏ vào ý

làm t tưởng bỏ :))))

**Comment by Dieungan99** [comment]
ồ à ý là bỏ vào cả 2 cái đó

**Comment by MinaNguyen99** [comment]
đúng rồi tức là có cả ý :)))

**Comment by MinaNguyen99** [comment]
xin lỗi tiếng địa phương :)))))

**Comment by NongThiMinh123** [comment]
thế phần word thì up lên git , rồi ai lam cái  nào thì sửa nhá

**Comment by Dieungan99** [comment]
ok

**Comment by Dieungan99** [comment]
vẫn là t lm cái bìa nha hihi

**Comment by NongThiMinh123** [comment]
ok ,m làm xong bia thì up lên git nha

**Comment by Dieungan99** [comment]
ok

**Comment by NongThiMinh123** [comment]
còn gì nữa mà khoảng thời gian cuối này mk cần làm nhỉ

**Comment by Dieungan99** [comment]
hoàn thiện nốt những cái chưa ổn thui á

**Comment by NongThiMinh123** [comment]
ok

**Comment by quynhnhi0124** [comment]
@NongThiMinh123  ơi lên xem pull request của t với
