### ISSUE TITLE
Thảo luận và phân công chi tiết sản phẩm

### ISSUE THREAD

**Issue by MinaNguyen99** [NongThiMinh123/SE03-Group12#23]
Cần phân công:
1 . Người làm trang hiển thị từng phần
2. Người làm trang chi tiết sản phẩm
3. Người làm trang giỏ hàng và thanh toán
4. Người làm quản lí đơn hàng

**Comment by quynhnhi0124** [comment]
thêm phần cho ng quản lí đơn hàng nữa m ơi

**Comment by quynhnhi0124** [comment]
t nhận phần quản lí giỏ hàng dc ko mn

**Comment by quynhnhi0124** [comment]
thanh toán luôn nữa,, hai phần í t thấy cũng liên quan

**Comment by MinaNguyen99** [comment]
Vậy nhi làm quản lí giỏ hàng nha

**Comment by MinaNguyen99** [comment]
> thêm phần cho ng quản lí đơn hàng nữa m ơi

OK nha

**Comment by Dieungan99** [comment]
t lm cái 1 nhé

**Comment by MinaNguyen99** [comment]
OK vậy ngân làm cái 1 nha

**Comment by quynhnhi0124** [comment]
tạo cái issue từng phần rồi assign riêng ra từng ng í My ạ

**Comment by MinaNguyen99** [comment]
ok ok

**Comment by MinaNguyen99** [comment]
Vậy @NongThiMinh123  c làm phần quản lí đơn hàng nha

**Comment by MinaNguyen99** [comment]
Mọi ng thảo luận tí nhở
