### ISSUE TITLE
Phân  công làm trang hiển thị từng phần

### ISSUE THREAD

**Issue by MinaNguyen99** [NongThiMinh123/SE03-Group12#25]
Ngân @Dieungan99  phụ trách làm hiển thị từng phần nha

**Comment by Dieungan99** [comment]
ok

**Comment by NongThiMinh123** [comment]
Ngân xkng phần này chưa

**Comment by Dieungan99** [comment]
nè các bạn ơi mấy nay bận ôn thi quá t quên ko push lên r, t vẫn đang lm nhá

**Comment by NongThiMinh123** [comment]
ok ,,t vẫn đang làm phần của t vừa làm vừa ôn thi

**Comment by Dieungan99** [comment]
mà mọi người chạy cái hiển thị hôm trc t push có vấn đề j ko?

**Comment by NongThiMinh123** [comment]
t thấy giao diện nó hơi bất ổn chút,, về cái giao diện cho nó sáng lên chút nhỉ

**Comment by Dieungan99** [comment]
hơi tối hả m?

**Comment by Dieungan99** [comment]
tại t cũng lm cho giống background trang chủ ý

**Comment by Dieungan99** [comment]
vậy để t xem lại nhá

**Comment by NongThiMinh123** [comment]
ok ,,
thế xem lại cái phần login của t nhưu thế co sduowjc k m

**Comment by NongThiMinh123** [comment]
có cần chỉnh sưa rj k

**Comment by Dieungan99** [comment]
t cũng có xem r á

**Comment by Dieungan99** [comment]
nhưng mà về máy t nó hơi lệch m ơi, m xem chỉnh lại font size xem sao nhá

**Comment by Dieungan99** [comment]
hay do máy t khác độ phân giải ý t cx ko rõ

**Comment by NongThiMinh123** [comment]
ừ ,tại cái máy t màn hình nó bị như thế dây 
nên nvafo máy mn thì chỉnh chút nha

**Comment by Dieungan99** [comment]
uh ok

**Comment by MinaNguyen99** [comment]
đợt này cũng hơi bận ôn thi quá nhưng mà mọi người vẫn cố gắng làm cả code nữa nha

**Comment by MinaNguyen99** [comment]
push muộn cũng k sao đến khi xong rồi push lên cũng đc
