### ISSUE TITLE
Phân công làm quản lí đơn hàng

### ISSUE THREAD

**Issue by MinaNguyen99** [NongThiMinh123/SE03-Group12#26]
@NongThiMinh123 Minh nhận làm quản lí đơn hàng.

**Comment by MinaNguyen99** [comment]
@NongThiMinh123  tình hình ntn rồi c?

**Comment by MinaNguyen99** [comment]
tình hình làm như thế nào rồi @NongThiMinh123

**Comment by quynhnhi0124** [comment]
quản lí đơn hàng hoàn thành, tính năng mua hàng hoàn thành luôn
