### ISSUE TITLE
Phân công làm trang chi tiết sản phẩm

### ISSUE THREAD

**Issue by MinaNguyen99** [NongThiMinh123/SE03-Group12#27]
@Hamyho  nhận làm trang chi tiết sản phẩm

**Comment by MinaNguyen99** [comment]
Quá trình viết đang gặp chút lỗi sau khi fix lỗi thì t up nha

**Comment by NongThiMinh123** [comment]
Ok..cứ xem qua..xong chỉnh giao diện phù hợp tý nha

**Comment by MinaNguyen99** [comment]
ok ok

**Comment by quynhnhi0124** [comment]
Ngân ơi cập nhật phần Controller để hiển thị dc nha c ơi
