### ISSUE TITLE
Thảo luận làm bản word

### ISSUE THREAD

**Issue by Dieungan99** [NongThiMinh123/SE03-Group12#34]

**Comment by Dieungan99** [comment]
alo các bạn ơi mình thảo luận đóng góp ý kiến làm bản word ở đây nhá

**Comment by MinaNguyen99** [comment]
ôi mình readme chưa hoàn thiện kìa

**Comment by MinaNguyen99** [comment]
đăng word ở bên ngoài nhia

**Comment by Dieungan99** [comment]
t vừa đưa cái bìa lên r đó
