### ISSUE TITLE
lỗi

### ISSUE THREAD

**Issue by NongThiMinh123** [NongThiMinh123/SE03-Group12#35]
![81781874_984554398598055_1561060774888079360_n](https://user-images.githubusercontent.com/54107714/71974853-2437f280-3245-11ea-8dfc-9931fe3e8f44.png)

**Comment by NongThiMinh123** [comment]
dây là cái lỗi j v mn ơi 
, sao chỗ này của t hôm nọ làm oke rôi giờ lại thành ra v nhỉ

**Comment by quynhnhi0124** [comment]
t sửa lại rồi,, vì hôm trc chưa xong cái detail nên lúc push lên t quên chưa comment lại nha

**Comment by quynhnhi0124** [comment]
chạy dc bình thường rồi, @NongThiMinh123  lên merge pull request của t với
