### ISSUE TITLE
Thảo luận các công việc cần phải làm trong project 

### ISSUE THREAD

**Issue by NongThiMinh123** [NongThiMinh123/SE03-Group12#6]
các bạn ơi ,,bọn mình thảo luận chút về những cônng việc sẽ được làm trong đề tài nha

**Comment by Dieungan99** [comment]
ok

**Comment by Dieungan99** [comment]
T có lên mạng tham khảo mấy web bán mỹ phẩm các bạn ạ

**Comment by Dieungan99** [comment]
Trang chủ thì header footer xong mấy trang sau kế thừa cửa trang chủ

**Comment by Dieungan99** [comment]
xong mình show sp theo từng phân mục nhỉ

**Comment by Dieungan99** [comment]
Cần database nữa vs mình phải xây dựng khóa ngoại mqh các kiểu cho các table nữa

**Comment by NongThiMinh123** [comment]
ừ đấy,, còn gj nữa khong nhỉ

**Comment by Dieungan99** [comment]
thế h mình tạo db nhờ. Gồm những table nào đây

**Comment by Dieungan99** [comment]
Mình quyết trc xem bán những j đã nha xong lm j thì lm tiếp

**Comment by NongThiMinh123** [comment]
oke nha,,vậy giờ để t them những công việc trên vào trong project nha

**Comment by quynhnhi0124** [comment]
db thì t nghĩ đơn giản thui, trang điểm, skincare, tóc, đồ tp chức năng...mn thấy thế nào
