### ISSUE TITLE
Thảo luận về công cụ thực hiện đề tài

### ISSUE THREAD

**Issue by Dieungan99** [NongThiMinh123/SE03-Group12#7]

**Comment by NongThiMinh123** [comment]
này .mọi người ơi, mình liệt kê ra các công cụ để thực hiện trogn dự án rồi ghi vào file readme.md nhỉ

**Comment by quynhnhi0124** [comment]
SQL để trữ database
Ngôn ngữ: PHP (+ HTML5, CSS, sử dụng thư viện Bootstrap)
Framework: Laravel
Như vậy đủ chưa mn nhỉ

**Comment by Dieungan99** [comment]
Mình có làm JavaScript nữa nhỉ?

**Comment by NongThiMinh123** [comment]
Mọi người từn này côgn cụ của mình đã được chưa ..add vào file readme di

**Comment by Dieungan99** [comment]
Uh cứ update file readme đi, có j trong lúc làm phát sinh thêm công cụ j thì mình bổ sung thêm

**Comment by NongThiMinh123** [comment]
oke nhé,,
