### ISSUE TITLE
Xác định yêu cầu và đặc tả ( Goals & Business Objectives ) + Use Case Diagram

### ISSUE THREAD

**Issue by quynhnhi0124** [NongThiMinh123/SE03-Group12#8]
T nghĩ là nên bắt đầu xây dựng yêu cầu và đặc tả cho sp như thầy đã dạy
Mn ơi mình đưa ra ý kiến về hai yto trên nha.

**Comment by quynhnhi0124** [comment]
Trang web sản phẩm bán mỹ phẩm người dùng mua hàng mà không cần đăng nhập, có tài khoản của nhân viên bán hàng.
Nhân viên có thể thêm, sửa, xóa sản phẩm, thay đổi chi tiết sản phẩm, quản lí đơn hàng
Khách hàng có thể xem thông tin chi tiết sản phẩm ( sản phẩm theo từng mục, tên sản phẩm, giá cả, thông tin giảm giá của từng sản phẩm), tìm kiếm sản phẩm, mua hàng mà không cần phải đăng kí người dùng.

**Comment by NongThiMinh123** [comment]
Mình thêm chức năng cho chủ cửa hàng ,chủ shop, quản lí nữa chứ

**Comment by NongThiMinh123** [comment]
Tại nếu đó là 1 shop lớn thì cần có người đứng ra quản lí , mà bây giờ các chức năng của ng quản lí sẽ làm những gì?  Mọi ng cùng nghĩ xem

**Comment by quynhnhi0124** [comment]
ừ, nên có quản lý để quản lí thêm các chức năng của nhân viên và giám sát tình hình

**Comment by NongThiMinh123** [comment]
Yêu cầu: thứ nhất về giao diện 
- Màu sắc chủ đạo của website phải hài hòa
- Các quảng cáo và menu có kích cỡ phù hợp, cân đối
- Cách thức thêm sản phẩm vào giỏ, đặt hàng,.... trên website phải được sắp xếp khoa học và dễ dàng sử dụng.
- Hình ảnh của sản phẩm cần rõ ràng

**Comment by NongThiMinh123** [comment]
Yêu cầu thứ 2 về tiện ích của website bọn mình làm: 
Khi khách hàng ghé thăm web sẽ thấy thoải mái hơn nếu tìm sản phẩm nhanh, sản phẩm có đủ thông tin để lựa chọn, thêm bào giỏ hàng và mua hàng nhanh chóng…Như vậy mình thiết kế web phải chú ý đến cách sắp xếp danh mục sản phẩm  nha

**Comment by NongThiMinh123** [comment]
Mọi người có thêm những yêu cầu gì bổ sung thêm vào dưới nha rồi mình add vào file readme.md

**Comment by NongThiMinh123** [comment]
alo alo ,mn ơi

**Comment by NongThiMinh123** [comment]
t thấy mình còn thiếu cái sơ đồ

**Comment by NongThiMinh123** [comment]
thì Nhi cuối tuần làm r gửi nhé

**Comment by quynhnhi0124** [comment]
oke cuối tuần t sẽ gửi nhóm

**Comment by quynhnhi0124** [comment]
T gửi mọi người Use Case Diagram, có gì thiếu mn góp í để t sửa lại nhé: 
![Untitled Diagram](https://user-images.githubusercontent.com/53897670/68489414-9efe8480-0279-11ea-929f-bb2af588524e.jpg)

**Comment by NongThiMinh123** [comment]
Ok Nhi.vậy là cũng khá ổn .bây giờ tạo thêm database nữa thôi

**Comment by NongThiMinh123** [comment]
cái issue này xong rồi t clone lại nha

**Comment by quynhnhi0124** [comment]
Ừ t xong rồi @NongThiMinh123 ơi

**Comment by NongThiMinh123** [comment]
ok
