### ISSUE TITLE
Nhóm bầu người làm thư kí

### ISSUE THREAD

**Issue by MinaNguyen99** [NongThiMinh123/SE03-Group12#9]
Nhiệm vụ của thư kí là ghi chép lại quá trình làm việc nhóm.
Hi  vọng mọi người cho ý kiến

**Comment by MinaNguyen99** [comment]
tớ đề cử bạn Ngân

**Comment by NongThiMinh123** [comment]
Ok, Ngân vs Nhi xem có ý kiến j k,

**Comment by quynhnhi0124** [comment]
oki t đồng í nha
